# Generated by Django 2.2.2 on 2019-08-09 12:50

from django.db import migrations


def load_setup_data(apps,schema_editor):
    """
    These creates the initial role and admin user. Use the details to login
    then change the email and password immediately once logged in.
    """
    DefaultRole = apps.get_model("accounts", "Role")
    DefaultUser = apps.get_model("accounts", "User")

    if DefaultRole.objects.count() == 0 and DefaultUser.objects.count == 0:
        DefaultRole.objects.create(name="admin", description="This is a system administrator role.")
        DefaultUser.objects.create_superuser("admin", "admin@info.com", "1234@admin")
    

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190731_1757'),
    ]

    operations = [
        migrations.RunPython(load_setup_data)
    ]
